#!/bin/bash -eux

[[ $(lsb_release -r|rev|cut -d' ' -f1|rev) == "20.04" ]] && \
    lsb_release -r && \
    echo "nothing to do" && \
    exit 0

apt update
apt upgrade -y
apt dist-upgrade -y

apt install -y update-manager-core
do-release-upgrade -q

echo "reboot in 10s"
reboot sleep 10
